name: Dart CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          # (Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN
          accessToken: secrets.OAUTH_ACCESS_TOKEN
          # (Required) Token from ~/.pub-cache/credentials.json. Use c
          refreshToken: secrets.OAUTH_ACCESS_TOKEN